### ISSUE TITLE
宁波地铁API

### ISSUE THREAD

**Issue by ihkk** [BobLiu0518/BLBot#7]
方便请教一下宁波地铁API`https://metroinfo.ditiego.net/Api/Stations/`是自己抓的吗，还是有相关文档可以参考？

**Comment by BobLiu0518** [comment]
> 方便请教一下宁波地铁API`https://metroinfo.ditiego.net/Api/Stations/`是自己抓的吗，还是有相关文档可以参考？

抓的。
